Rental1/Rental1/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

from django.urls import include

urlpatterns += [
    path('rentals/', include('rentals.urls', namespace='rentals')),
]

urlpatterns += [
    path('rentalsexternalcss/', include('rentalsexternalcss.urls', namespace='rentalsexternalcss')),
]

urlpatterns += [
    path('rentalstemplates/', include('rentalstemplates.urls', namespace='rentalstemplates')),
]


urlpatterns += [
    path('rentalsescaping/', include('rentalsescaping.urls', namespace='rentalsescaping')),
]

urlpatterns += [
    path('rentalsmodel/', include('rentalsmodel.urls', namespace='rentalsmodel')),
]

Rental1/rentals/urls.py
from django.urls import path
from . import views
app_name = 'rentals'
urlpatterns = [
    path('', views.index, name='index'),
    path('review/', views.review, name='review'),
    ]

Rental1/rentalsescaping/urls.py
from django.urls import path
from . import views
app_name = "rentalsescaping"
urlpatterns = [
    path('', views.index3, name='index'),
    path('review/', views.review3, name='review'),
    ]

Rental1/rentalsexternalcss/urls.py
from django.urls import path
from . import views
app_name = "rentalsexternalcss"
urlpatterns = [
    path('', views.index, name='index'),
    path('review/', views.review, name='review'),
    ]

Rental1/rentalsmodel/urls.py
from django.urls import path
from . import views
app_name = 'rentalsmodel'
urlpatterns = [
    path('', views.index, name='index'),
    path('review/', views.review, name='review'),
    ]

Rental1/rentalstemplates/urls.py
from django.urls import path
from . import views
app_name = 'rentalstemplates'
urlpatterns = [
    path('', views.index, name='index'),
    path('review/', views.review, name='review'),
    ]

Rental1/rentals/models.py
from django.db import models

# Create your models here.

Rental1/rentalsescaping/models.py
from django.db import models

# Create your models here.

Rental1/rentalsexternalcss/models.py
from django.db import models

# Create your models here.

Rental1/rentalsmodel/models.py
from django.db import models

# Create your models here.

Rental1/rentalstemplates/models.py
from django.db import models

# Create your models here.

Rental1/rentals/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
 #   return HttpResponse("Hello from My App!")
    return render(request, 'rentals/home.html')

def review(request):
    return render(request, 'rentals/review.html')

Rental1/rentalsescaping/views.py
from django.shortcuts import render

# Create your views here.
def index3(request):
 #   return HttpResponse("Hello from My App!")
    active_class = "index"
    harmful_variable = "<script>alert('hello')</script>"
    #harmful_variable = "<script>window.location= 'http://harmfulsite/mypage'</script>"
    context = {
        'active_class': active_class,
        'harmful_variable':harmful_variable,
    }
    return render(request, 'rentalsescaping/home.html', context)

def review3(request):
    active_class = "review"
    harmful_variable = "<script>alert('hello')</script>"
    context = {
        'active_class': active_class,
        'harmful_variable':harmful_variable,
    }
    return render(request, 'rentalsescaping/review.html', context)

Rental1/rentalsexternalcss/views.py
from django.shortcuts import render

# Create your views here.
# Create your views here.
def index(request):
 #   return HttpResponse("Hello from My App!")
    return render(request, 'rentalsextenalcss/home.html')

def review(request):
    return render(request, 'rentalsextenalcss/review.html')

Rental1/rentalsmodel/views.py
from django.shortcuts import render

# Create your views here.
# Create your views here.
def index(request):
 #   return HttpResponse("Hello from My App!")
    active_class = "index"
    harmful_variable = "<script>alert('hello')</script>"
    context = {
        'active_class': active_class,
        'harmful_variable':harmful_variable,
    }
    return render(request, 'rentalsmodel/home.html', context)

def review(request):
    active_class = "review"
    harmful_variable = "<script>alert('hello')</script>"
    context = {
        'active_class': active_class,
        'harmful_variable':harmful_variable,
    }
    return render(request, 'rentalsmodel/review.html', context)

Rental1/rentalstemplates/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
 #   return HttpResponse("Hello from My App!")
    active_class = "index"
    context = {
        'active_class': active_class,
    }
    return render(request, 'rentalstemplates/home.html', context)

def review(request):
    active_class = "review"
    context = {
        'active_class': active_class,
    }
    return render(request, 'rentalstemplates/review.html', context)

Rental1/rentals/templates/rentals/home.html
<html>
 <head>
   <title>Property display</title>
   
<style>
  body {
    margin: 0;
    
}

ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    width: 15%;
    background-color: #f1f1f1;
    position: fixed;
    height: 100%;
    overflow: auto;
}

 li a {
    display: block;
    color: #000;
    padding: 8px 16px;
    text-decoration: none;
}

li a.active {
    background-color: #4CAF50;
    color: white;
}

li a:hover:not(.active) {
    background-color: #555;
    color: white;
}

h3 {
    color:purple;
    text-transform:uppercase;
}
  </style>
   
 </head>
 <body>
  <!-- Reference https://www.w3schools.com/css/css_navbar.asp-->
  <nav>
    <ul>
      <li><a href="{% url 'rentals:index' %}" class="active">Home</a></li>
      <li><a >Our houses</a></li>
      <li><a >Owners</a></li>
      <li><a href="{% url 'rentals:review' %}">Review</a></li>
      <li><a >Contact</a></li>
      <li><a >About</a></li>
    </ul>
 </nav>
 <main>
  <div style="margin-left:15%;padding:1px 16px;height:1000px;">
  <h3 style="text-transform: lowercase;color:red">Our Top Rated Properties</h3>
  <h3>test h3</h3>
  <p>
   Contemporary house<br/>
   {% load static %}
   <img src="{% static 'images/house1.jpeg' %}"/>
  </p>
  <p>
   Beach house<br/>
   
   <img src="{% static 'images/house2.jpeg' %}"/>
  </p>
  </div>
 </main>
 </body>
</html>

Rental1/rentals/templates/rentals/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<title>My first html page</title>
</head>
 <body>
  <p>
	<h1>Welcome to you all</h1>
	These are the <span style="color: blue; text-transform: uppercase;"> cheap places </span> 
	This is our first web page
	<h3>List of houses</h3>
	{% load static %}
	<img src="{% static 'images/house1.jpeg' %}" alt="image of a house"/>
	<table border='1'> 
		<thead>
			<tr>
			<th>Owner</th>
			<th>Address</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Anwar</td>
				<td rowspan="2">Vacoas</td>
			</tr>
			<tr>
				<td>Alyaan</td>
				
			</tr>
			<tr>
				<td colspan="2" rowspan="2">Shihaab</td>
				
			</tr>
			<tr>
				
			</tr>
			<tr>
				<td>Shihaab</td>
				<td>Reduit</td>
			</tr>
		</tbody>	

	</table>
	<div style="color: red; display:block">
		<p>These are the luxurious places</p>
		<p>That you will find at affordable prices</p>
	</div>
  </p>
 </body>
</html>

Rental1/rentals/templates/rentals/review.html
<html>
 <head>
   <title>Property Review</title>
   
 <style type="text/css">
   
 body {
    margin: 0;
}

ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    width: 15%;
    background-color: #f1f1f1;
    position: fixed;
    height: 100%;
    overflow: auto;
}

 li a {
    display: block;
    color: #000;
    padding: 8px 16px;
    text-decoration: none;
}

li a.active {
    background-color: #4CAF50;
    color: white;
}

li a:hover:not(.active) {
    background-color: #555;
    color: white;
}

h3 {
    color:purple;
    text-transform:uppercase;
}
   
 </style>
 </head>
 <body>
  <!-- Reference https://www.w3schools.com/css/css_navbar.asp-->
  <nav>
  <ul>
    <li><a href="/rentals/">Home</a></li>
    <li><a >Our houses</a></li>
    <li><a >Owners</a></li>
    <li><a href="/rentals/review" class="active" >Review</a></li>
    <li><a >Contact</a></li>
    <li><a >About</a></li>
  </ul>
</nav>
<main>
  <div style="margin-left:15%;padding:1px 16px;height:1000px;">
  <h3 >Please review your stay</h3>
  <h3 style="color:red;">Give genuine feedback</h3>
  
  <p>
   <form action="review_pro" method="get" >
     <fieldset>
      <legend>Personal Details:</legend>
	Name : <br/>
	<input type="text" value="" name="txt_name" title="Name should consist of one or more words, starting with an uppercase letter followed by lowercase characters, and separated by spaces" maxlength="16" size="50" pattern="[A-Z][a-z]+( [A-Z][a-z]+)*$" required /><br/><br/>
	
	
  Title: <br/>
		<input type="radio" name="txt_gender" value="male" required/> Male
  	<input type="radio" name="txt_gender" value="female" /> Female
  	<input type="radio" name="txt_gender" value="other" /> Other <br/><br/>
     </fieldset>
	<!-- multiple, size -->
     <fieldset>
      <legend>Property Details:</legend>
	<h5>Please give us feedback on your appreciation of the property</h5> 
	Cleanliness : <br/>
	 <select name="txt_clean_rating" size ="2" multiple='true' >
 	 <option value="" selected>Please select a value</option>
	 <option value= "1" >one</option>
	 <option value= "2" >two</option>
	 <option value= "3" >3</option>
	 <option value= "4" >4</option>
	 <option value= "5" >5</option>
	</select><br/><br/>
	Comment: </br>
	<textarea  rows="10" cols="130" name="txt_comment"></textarea><br/><br/>
	<button type="button" onclick="alert('Hello World!')">Click Me!</button> <br/><br/>
	<input type="submit"/> 
	<input type="reset"/>


   </form>
  </p>
  </div>
</main>
 </body>
</html>

Rental1/rentalsescaping/templates/rentalsescaping/base.html
<html>
 <head>
  <title>{% block title %}My amazing site{% endblock %}</title>
   
   {% load static %}
   <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"> 
   
 </head>
 <body>
  <!-- Reference https://www.w3schools.com/css/css_navbar.asp-->
  <nav>
    {% block navbar %}
    <ul>
      <li><a href="{% url 'rentalsescaping:index' %}" 
        {% if active_class == "index" %} class="active" {% endif %}>Home</a></li>
      <li><a >Our houses</a></li>
      <li><a >Owners</a></li>
      <li><a href="{% url 'rentalsescaping:review' %}" 
        {% if active_class == "review" %} class="active" {%endif%}>Review</a></li>
      <li><a >Contact</a></li>
      <li><a >About</a></li>
      <li><a >Rentals Escaping</a></li>
    </ul>
    {% endblock %}
 </nav>
 <main>
  <div style="margin-left:15%;padding:1px 16px;height:1000px;">
    {% block content %}{% endblock %}
  </div>
 </main>
 </body>
</html>

Rental1/rentalsescaping/templates/rentalsescaping/home.html
{% extends "rentalsescaping/base.html" %}

{% block title %}Property Rental {% endblock title%}

{% block content %}
<h3 style="text-transform: lowercase;">Our Top Rated Properties</h3>
  <h3>test h3</h3>
  <p>
   Contemporary house1<br/>
   {% load static %}
   <img src="{% static 'images/house1.jpeg' %}"/>
  </p>
  <p>
   Beach house<br/>
   
   <img src="{% static 'images/house2.jpeg' %}"/>
  </p>
  
  Escaped Harmful Variable {{ harmful_variable }}
 
  {% autoescape off %}
  UnEscaped Harmful Variable {{ harmful_variable }}
  {% endautoescape %}
  Escaped Harmful Variable {{ harmful_variable }}
  Unescaped Harmful Variable {{ harmful_variable|safe}}
  {% endblock content %}
  
  

Rental1/rentalsescaping/templates/rentalsescaping/review.html
{% extends "rentalsescaping/base.html" %}

{% block title %}Property Review {% endblock title%}

{% block content %}
  <h3 >Please review your stay escaping</h3>
  <h3 style="color:red;">Give genuine feedback</h3>
  

   <form action="review" method="get" >
     <fieldset>
      <legend>Personal Details:</legend>
	Name : <br/>

	<input type="text" value="" name="txt_name" title="Name should consist of one or more words, starting with an uppercase letter followed by lowercase characters, and separated by spaces" maxlength="16" size="50" 
	pattern="[A-Z][a-z]+( [A-Z][a-z]+)+" required /><br/><br/>
	Email : <br/>
	<input type="email" value="" name="txt_email"  required /><br/><br/>
	ID : <br/>
	<input type="number" value="" name="txt_id"  required /><br/><br/>
	
	Title: <br/>
	<input type="radio" name="txt_gender" value="male" required/> Male
  	<input type="radio" name="txt_gender" value="female" /> Female
  	<input type="radio" name="txt_gender" value="other" /> Other <br/><br/>
     </fieldset>
	<!-- multiple, size -->
     <fieldset>
      <legend>Property Details:</legend>
	<h5>Please give us feedback on your appreciation of the property</h5> 
	Cleanliness : <br/>
	 <select name="txt_clean_rating" size='2' multiple='true' >
 	 <option value="" selected>Please select a value</option>
	 <option value= "1" >one</option>
	 <option value= "2" >two</option>
	 <option value= "3" >3</option>
	 <option value= "4" >4</option>
	 <option value= "5" >5</option>
	</select><br/><br/>
	Comment: </br>
	<textarea  rows="10" cols="130" name="txt_comment"></textarea><br/><br/>
	<button type="button" onclick="alert('Hello World!')">Click Me!</button> <br/><br/>
	<input type="submit"/> 
	<input type="reset"/>
   </form>
   {% endblock content%}

Rental1/rentalsexternalcss/templates/rentalsextenalcss/home.html
<html>
 <head>
   <title>Property display</title>
   
   {% load static %}
   <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"> 
   
 </head>
 <body>
  <!-- Reference https://www.w3schools.com/css/css_navbar.asp-->
  <nav>
    <ul>
      <li><a href="{% url 'rentalsexternalcss:index' %}" class="active">Home</a></li>
      <li><a >Our houses</a></li>
      <li><a >Owners</a></li>
      <li><a href="{% url 'rentalsexternalcss:review' %}">Review</a></li>
      <li><a >Contact</a></li>
      <li><a >About</a></li>
    </ul>
 </nav>
 <main>
  <div style="margin-left:15%;padding:1px 16px;height:1000px;">
  <h3 style="text-transform: lowercase;">Our Top Rated Properties</h3>
  <h3>test h3</h3>
  <p>
   Contemporary house1<br/>
   {% load static %}
   <img src="{% static 'images/house1.jpeg' %}"/>
  </p>
  <p>
   Beach house<br/>
   
   <img src="{% static 'images/house2.jpeg' %}"/>
  </p>
  </div>
 </main>
 </body>
</html>

Rental1/rentalsexternalcss/templates/rentalsextenalcss/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<title>My first html page</title>
</head>
 <body>
  <p>
	<h1>Welcome to you all</h1>
	These are the <span style="color: blue; text-transform: uppercase;"> cheap places </span> 
	This is our first web page
	<h3>List of houses</h3>
	{% load static %}
	<img src="{% static 'images/house1.jpeg' %}" alt="image of a house"/>
	<table border='1'> 
		<thead>
			<tr>
			<th>Owner</th>
			<th>Address</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Anwar</td>
				<td rowspan="2">Vacoas</td>
			</tr>
			<tr>
				<td>Alyaan</td>
				
			</tr>
			<tr>
				<td colspan="2" rowspan="2">Shihaab</td>
				
			</tr>
			<tr>
				
			</tr>
			<tr>
				<td>Shihaab</td>
				<td>Reduit</td>
			</tr>
		</tbody>	

	</table>
	<div style="color: red; display:block">
		<p>These are the luxurious places</p>
		<p>That you will find at affordable prices</p>
	</div>
  </p>
 </body>
</html>

Rental1/rentalsexternalcss/templates/rentalsextenalcss/review.html
<html>
 <head>
   <title>Property Review</title>
   
   {% load static %}
   <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"> 
   
 </head>
 <body>
  <!-- Reference https://www.w3schools.com/css/css_navbar.asp-->
  <nav>
  <ul>
    <li><a href="/rentalsexternalcss/">Home</a></li>
    <li><a >Our houses</a></li>
    <li><a >Owners</a></li>
    <li><a href="/rentalsexternalcss/review" class="active" >Review</a></li>
    <li><a >Contact</a></li>
    <li><a >About</a></li>
  </ul>
</nav>
<main>
  <div style="margin-left:15%;padding:1px 16px;height:1000px;">
  <h3 >Please review your stay</h3>
  <h3 style="color:red;">Give genuine feedback</h3>
  
  <p>
   <form action="review.php" method="post" >
     <fieldset>
      <legend>Personal Details:</legend>
	Name : <br/>
	<input type="text" value="" name="txt_name" title="Name should consist of one or more words, starting with an uppercase letter followed by lowercase characters, and separated by spaces" maxlength="16" size="50" pattern="[A-Z][a-z]+( [A-Z][a-z]+)*$" required /><br/><br/>
	Title: <br/>
		<input type="radio" name="txt_gender" value="male" required/> Male
  	<input type="radio" name="txt_gender" value="female" /> Female
  	<input type="radio" name="txt_gender" value="other" /> Other <br/><br/>
     </fieldset>
	<!-- multiple, size -->
     <fieldset>
      <legend>Property Details:</legend>
	<h5>Please give us feedback on your appreciation of the property</h5> 
	Cleanliness : <br/>
	 <select name="txt_clean_rating" size ="2" multiple='true' >
 	 <option value="" selected>Please select a value</option>
	 <option value= "1" >one</option>
	 <option value= "2" >two</option>
	 <option value= "3" >3</option>
	 <option value= "4" >4</option>
	 <option value= "5" >5</option>
	</select><br/><br/>
	Comment: </br>
	<textarea  rows="10" cols="130" name="txt_comment"></textarea><br/><br/>
	<button type="button" onclick="alert('Hello World!')">Click Me!</button> <br/><br/>
	<input type="submit"/> 
	<input type="reset"/>


   </form>
  </p>
  </div>
</main>
 </body>
</html>

Rental1/rentalsmodel/templates/rentalsmodel/base.html
<html>
 <head>
  <title>{% block title %}My amazing site{% endblock  %}</title>
   
   {% load static %}
   <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"> 
   
 </head>
 <body>
  <!-- Reference https://www.w3schools.com/css/css_navbar.asp-->
  <nav>
    {% block navbar %}
    <ul>
      <li><a href="{% url 'rentalsmodel:index' %}" 
        {% if active_class == "index" %} class="active" {% endif %}>Home</a></li>
      <li><a >Our houses</a></li>
      <li><a >Owners</a></li>
      <li><a href="{% url 'rentalsmodel:review' %}" 
        {% if active_class == "review" %} class="active" {%endif%}>Review</a></li>
      <li><a >Contact</a></li>
      <li><a >About</a></li>
      <li><a >RentalsModel</a></li>
    </ul>
    {% endblock %}
 </nav>
 <main>
  <div style="margin-left:15%;padding:1px 16px;height:1000px;">
    {% block content %}{% endblock %}
  </div>
 </main>
 </body>
</html>

Rental1/rentalsmodel/templates/rentalsmodel/home.html
{% extends "rentalsmodel/base.html" %}

{% block title %}Property Rental {% endblock title%}

{% block content %}
<h3 style="text-transform: lowercase;">Our Top Rated Properties</h3>
  <h3>test h3</h3>
  <p>
   Contemporary house1<br/>
   {% load static %}
   <img src="{% static 'images/house1.jpeg' %}"/>
  </p>
  <p>
   Beach house<br/>
   
   <img src="{% static 'images/house2.jpeg' %}"/>
  </p>
{% endblock content %}
  
  

Rental1/rentalsmodel/templates/rentalsmodel/review.html
{% extends "rentalsmodel/base.html" %}

{% block title %}Property Review {% endblock title%}

{% block content %}
  <h3 >Please review your stay</h3>
  <h3 style="color:red;">Give genuine feedback</h3>
  

   <form action="review.php" method="post" >
     <fieldset>
      <legend>Personal Details:</legend>
	Name : <br/>
	<input type="text" value="" name="txt_name" title="Name should consist of one or more words, starting with an uppercase letter followed by lowercase characters, and separated by spaces" maxlength="16" size="50" pattern="[A-Z][a-z]+( [A-Z][a-z]+)*$" required /><br/><br/>
	Title: <br/>
		<input type="radio" name="txt_gender" value="male" required/> Male
  	<input type="radio" name="txt_gender" value="female" /> Female
  	<input type="radio" name="txt_gender" value="other" /> Other <br/><br/>
     </fieldset>
	<!-- multiple, size -->
     <fieldset>
      <legend>Property Details:</legend>
	<h5>Please give us feedback on your appreciation of the property</h5> 
	Cleanliness : <br/>
	 <select name="txt_clean_rating" size ="2" multiple='true' >
 	 <option value="" selected>Please select a value</option>
	 <option value= "1" >one</option>
	 <option value= "2" >two</option>
	 <option value= "3" >3</option>
	 <option value= "4" >4</option>
	 <option value= "5" >5</option>
	</select><br/><br/>
	Comment: </br>
	<textarea  rows="10" cols="130" name="txt_comment"></textarea><br/><br/>
	<button type="button" onclick="alert('Hello World!')">Click Me!</button> <br/><br/>
	<input type="submit"/> 
	<input type="reset"/>
   </form>
   {% endblock content%}

Rental1/rentalstemplates/templates/rentalstemplates/base.html
<html>
 <head>
  <title>{% block title %}My amazing site{% endblock  %}</title>
   
   {% load static %}
   <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"> 
   
 </head>
 <body>
  <!-- Reference https://www.w3schools.com/css/css_navbar.asp-->
  <nav>
    {% block navbar %}
    <ul>
      <li><a href="{% url 'rentalstemplates:index' %}" 
        {% if active_class == "index" %} class="active" {% endif %}>Home</a></li>
      <li><a >Our houses</a></li>
      <li><a >Owners</a></li>
      <li><a href="{% url 'rentalstemplates:review' %}" 
        {% if active_class == "review" %} class="active" {%endif%}>Review</a></li>
      <li><a >Contact</a></li>
      <li><a >About</a></li>
      <li><a >Rental Templates</a></li>
    </ul>
    {% endblock %}
 </nav>
 <main>
  <div style="margin-left:15%;padding:1px 16px;height:1000px;">
    {% block content %}{% endblock %}
  </div>
 </main>
 </body>
</html>

Rental1/rentalstemplates/templates/rentalstemplates/home.html
{% extends "rentalstemplates/base.html" %}

{% block title %}Property Rental {% endblock title%}

{% block content %}
<h3 style="text-transform: lowercase;">Our Top Rated Properties</h3>
  <h3>test h3</h3>
  <p>
   Contemporary house1<br/>
   {% load static %}
   <img src="{% static 'images/house1.jpeg' %}"/>
  </p>
  <p>
   Beach house<br/>
   
   <img src="{% static 'images/house2.jpeg' %}"/>
  </p>
{% endblock content %}
  
  

Rental1/rentalstemplates/templates/rentalstemplates/review.html
{% extends "rentalstemplates/base.html" %}

{% block title %}Property Review {% endblock title%}

{% block content %}
  <h3 >Please review your stay</h3>
  <h3 style="color:red;">Give genuine feedback</h3>
  

   <form action="review.php" method="post" >
     <fieldset>
      <legend>Personal Details:</legend>
	Name : <br/>
	<input type="text" value="" name="txt_name" title="Name should consist of one or more words, starting with an uppercase letter followed by lowercase characters, and separated by spaces" maxlength="16" size="50" pattern="[A-Z][a-z]+( [A-Z][a-z]+)*$" required /><br/><br/>
	Title: <br/>
		<input type="radio" name="txt_gender" value="male" required/> Male
  	<input type="radio" name="txt_gender" value="female" /> Female
  	<input type="radio" name="txt_gender" value="other" /> Other <br/><br/>
     </fieldset>
	<!-- multiple, size -->
     <fieldset>
      <legend>Property Details:</legend>
	<h5>Please give us feedback on your appreciation of the property</h5> 
	Cleanliness : <br/>
	 <select name="txt_clean_rating" size ="2" multiple='true' >
 	 <option value="" selected>Please select a value</option>
	 <option value= "1" >one</option>
	 <option value= "2" >two</option>
	 <option value= "3" >3</option>
	 <option value= "4" >4</option>
	 <option value= "5" >5</option>
	</select><br/><br/>
	Comment: </br>
	<textarea  rows="10" cols="130" name="txt_comment"></textarea><br/><br/>
	<button type="button" onclick="alert('Hello World!')">Click Me!</button> <br/><br/>
	<input type="submit"/> 
	<input type="reset"/>
   </form>
   {% endblock content%}